runtime: php55
api_version: 2

env_variables:
  MYSQL_DSN: 'mysql:unix_socket=/cloudsql/phpapi-222601:us-west1:api-db;dbname=api_db'
  MYSQL_USER: 'root'
  MYSQL_PASS: 'ydsgnYdsgn'

handlers:

- url: /(.+\.php)$
  script: \1

- url: /
  script: helloworld.php

